### ISSUE TITLE
Transparency background in 2022.08.23

### ISSUE THREAD

**Issue by Eddict** [khpylon/MachEWidget#34]
the transparency background in/since 2022.08.23 is incorrect in the widget itself and in the intro page, but not in the settings...
i have a dark/black background, transparency enabled and it was all good before this release.

<img src="https://user-images.githubusercontent.com/14122921/186242036-c82fa4e5-cf7b-4c84-9a91-b872868e3728.png" alt="Screenshot_20220823-205738_copy_720x1440" width="33%" height="33%"><img src="https://user-images.githubusercontent.com/14122921/186242050-a59d579a-7854-4673-ac53-c018ce23ad1c.png" alt="Screenshot_20220823-205722_copy_720x1440" width="33%" height="33%"><img src="https://user-images.githubusercontent.com/14122921/186242047-6d8dbef7-84eb-4638-bc16-ba66d003d0bf.png" alt="Screenshot_20220823-205758_copy_720x1440" width="33%" height="33%">

**Comment by khpylon** [comment]
Which phone model and version of Android are you using?

**Comment by Eddict** [comment]
a Sony Xperia XZ3 (H9436) running Android 10

**Comment by khpylon** [comment]
Did you upgrade to 2022.08.20 last weekend or were you running 2022.08.13 or earlier?  I had to make changes for the dark mode with Android 13.  

However, I didn't touch the code for the widget transparency.  If you turn transparency off in settings, it display in all black?

**Comment by Eddict** [comment]
i just upgraded, always running the latest version as soon as i get the update available notification.
with transparency off the widget has black background again but the intro remains as is/white.

**Comment by khpylon** [comment]
> i just upgraded, always running the latest version as soon as i get the update available notification. with transparency off the widget has black background again but the intro remains as is/white.

Unfortunately I only noticed this morning that I didn't put the 2022.08.20 date into the change log, so the update notification likely didn't show up.  If you send me a DM on whichever forum you're on (Mach-E/F150/Bronco), I can brew some special builds for you so we can try to diagnose what's going on.

**Comment by khpylon** [comment]
I'm not able to get the dark mode webview in my Android 10 emulator either, and part of the problem there is an old version of the Android System WebView app.  What I've found so far is the app need to be version 76.xxx or above.  Try this: open the Play Store app, search for "Webview", click on the installed version of this app in the list, scroll down to "About" and click on it, then check your version number.

**Comment by khpylon** [comment]
I confirmed a later version of System Webview is needed, but no longer relevant in your case.  The problem is a bug I introduced when updating the SDK.  I misread the documentation, so dark mode only works on Android 13.  That will be fixed in the next release.  The issue with transparency in the widget is a separate problem.

**Comment by khpylon** [comment]
I pushed a beta version to GitHub with the fix for dark mode.  Click [here](https://github.com/khpylon/MachEWidget/blob/master/app/github/release/app-release.apk?raw=true) to sideload it, and let me know if it works for you.

**Comment by Eddict** [comment]
yes that version works! (for the widget itself at least, the intro page still shows white sections as in the earlier screenshot)
thanks a lot for your time and effort 👍🏽

**Comment by khpylon** [comment]
Did the 2022.08.25 release fix the white sections in the webviews?

**Comment by Eddict** [comment]
the beta version (still) shows version 2022.08.23. and if i select Check For Update it does **not** show me the new version found notification. i will download and sideload it again to see if it has been solved.

**Comment by khpylon** [comment]
Try sideloading using the link in the prior message; it points at the latest version.

**Comment by Eddict** [comment]
sorry, was away for holidays. using .29 now but the issue still there in the webviews

**Comment by khpylon** [comment]
Sorry, I'm I think Google must have changed something in the WebView services.  It's working on Android 11 and above and I verified that the proper call is being made on Android 10 also.

**Comment by Eddict** [comment]
no problem. the widget (and the settings) are correct again and way more important
